const fs = require('fs'); const f = __dirname + '/overrides.json'; const o = JSON.parse(fs.readFileSync(f));
const srv = 'Record API (POST /modules/{id}/records with layout_id = default layout, field placed on that layout) accepts the bad value: ';
Object.assign(o, {
  I1: { id: 'I1', verdict: 'PASS', note: 'New Fields palette has 32 types (incl. the leftover TestDataType); system-only Department, Team and Pipeline are not offered' },
  I2: { id: 'I2', verdict: 'PASS', note: 'Clicking Single Line adds the field; "Custom Fields Left" 512 → 511; Save creates it (POST /modules/{id}/fields {fields:[{fieldName, labels, datatypeKey, required, unique}]})' },
  I3: { id: 'I3', verdict: 'NOT RUN', note: 'filling 512 fields was not run in this pass (time); limit is client-side 512 per layout' },
  I4: { verdict: 'PASS', note: 'Required custom field is enforced when the field is on the record\'s layout: record without it → 422 RECORD_VALIDATION_FAILED (path qa_req_ro, type required); with it → 201. (Without the field on any layout the API accepts the record — see F9 for the record-name field.)' },
  I5: { verdict: 'INCONCLUSIVE', note: 'Field Properties → PERMISSIONS of a required field: the Read-only switch is enabled and the hint "A required field can\'t be read-only — remove Required first." is not shown. After switching it on and saving, read_only was not stored (either the click missed or it is dropped silently) — the save-time guard "Cannot save: … both Required and Read-only" could not be confirmed.', shot: 'screenshots/I5-required-readonly.png' },
  I6: { verdict: 'PASS', note: 'Unique: second "abc" → 422 RECORD_VALIDATION_FAILED; "ABC" and " abc " also refused (case- and space-insensitive)' },
  I7: { id: 'I7', verdict: 'NOT RUN', note: 'unique across modules needs a second QA module with the same API name — not run in this pass' },
  I8: { id: 'I8', verdict: 'PASS', note: 'Data-type capability flags: lookup, multi-select, address, file, image have can_set_unique=false; builder greys out "Mark as Unique" on a pick list (seen on Priority)' },
  I9: { id: 'I9', verdict: 'NOT RUN', note: 'full/half width toggle not automated' },
  I10: { id: 'I10', verdict: 'PASS', note: 'Field menu of a required field (Calls Subject) shows "Remove from Layout" disabled — "Required fields stay on every layout. Turn off Required first."' },
  I11: { verdict: 'FAIL', severity: 'Low', note: 'Field label limit is client-side only: POST field with a 51-character label → 201 (UI limit 50). EN/AR/FR labels stored correctly; <img onerror> label stored as text.' },
  I12: { verdict: 'PASS', note: 'API name rules: "1abc", "a-b", Arabic → 400 FIELD_NAME_INVALID; "a b" accepted and normalised to a_b; duplicate "Single_Line" → 409 FIELD_ALREADY_EXISTS' },
  I13: { verdict: 'FAIL', severity: 'High', note: 'A saved field\'s data type can be changed: PUT /modules/{id}/fields/{fieldId} with datatypeKey single_line → number returns 200 and the field becomes number (Zoho: "the field type cannot be changed"). Existing values are not converted.' },
  I14: { verdict: 'FAIL', severity: 'High', note: srv + 'single line with max_length 10 saves an 11-character value (201). Option bound OK: max_length 20001 → 400 DATATYPE_OPTION_TOO_LARGE.' },
  I15: { verdict: 'PASS' },
  I16: { verdict: 'FAIL', severity: 'High', note: srv + 'number field with min 0 / max 100 saves 101 and -1; "abc" is stored as a string in a number field; "15,000" stored as 15000. Currency symbol "EGP12" (UI max 4) is not stored at all via the field API.' },
  I17: { verdict: 'FAIL', severity: 'Medium', note: srv + 'date "not a date", 2026-02-29 (not a leap year) and date-time "yesterday" are all saved as plain strings.' },
  I18: { verdict: 'FAIL', severity: 'High', note: srv + 'email "not-an-email", phone "call me" and URL "javascript:alert(1)" are saved (201). The javascript: URL is a stored-XSS risk wherever the URL is rendered as a link.' },
  I19: { id: 'I19', verdict: 'NOT RUN', note: 'checkbox default value not automated' },
  I20: { verdict: 'FAIL', severity: 'High', note: 'Duplicate options refused (400 DATATYPE_OPTION_DUPLICATE); Arabic and html option text kept. ' + srv + 'pick-list value "Delta" that is not in the list is saved (201).' },
  I21: { id: 'I21', verdict: 'NOT RUN', note: 'option-replacement dialog not automated (value-usage endpoint exists)' },
  I22: { verdict: 'FAIL', severity: 'Medium', note: srv + 'multi-select with max_items 2 saves 3 values.' },
  I23: { id: 'I23', verdict: 'NOT RUN', note: 'radio / status types not automated' },
  I24: { id: 'I24', verdict: 'NOT RUN', note: 'default values not automated' },
  I25: { verdict: 'FAIL', severity: 'High', note: 'Builder: regex box, "Invalid regular expression" for "([" and the tester (✓ matches / ✗ does not match) work, and the regex is saved into the layout ("regex":"^[A-Z]{2}[0-9]{4}$"). ' + srv + '"ab12" is saved (201) — the regex is not enforced on the server.' },
  I26: { verdict: 'INCONCLUSIVE', note: 'regex (a+)+$ with 32×"a"+"b" answered in 119 ms, but regex is not enforced server-side (I25), so catastrophic backtracking was never exercised' },
  I27: { id: 'I27', verdict: 'NOT RUN', note: 'conditional visibility not automated' }, I28: { id: 'I28', verdict: 'NOT RUN', note: 'not automated' }, I29: { id: 'I29', verdict: 'NOT RUN', note: 'auto-fill not automated (NDC-1231 open)' },
  I30: { verdict: 'PASS', note: 'Auto number QA-####-EG, start 7, increment 2: existing records are numbered first, new records continue (QA-0079-EG, QA-0081-EG …); 5 parallel creates all unique' },
  I31: { verdict: 'PASS' },
  I32: { verdict: 'FAIL', severity: 'Low', note: 'Lookup to Contacts → 201, but a second lookup to Contacts with the same related-list title "QA MF Devices" is also accepted (201) — the title is supposed to be unique among lookups pointing at the same module.' },
  I33: { verdict: 'FAIL', severity: 'Low', note: 'Multi-module lookup with target_modules [] is accepted (201); the UI says "Select at least one module".' },
  I34: { verdict: 'PASS' }, I35: { verdict: 'PASS' },
  I36: { id: 'I36', verdict: 'NOT RUN', note: 'rollup needs a second module with a lookup back — not run' }, I37: { id: 'I37', verdict: 'NOT RUN', note: 'quick-create trigger not automated' }, I38: { id: 'I38', verdict: 'NOT RUN', note: 'file/image upload not automated' },
  I39: { verdict: 'PASS', note: 'Address saved as an object (street, city, country) when sent as {kind:object, properties}' },
  I40: { verdict: 'PASS', note: 'Rich text with <script> and <img onerror> is stored unsanitised (201) but the record page renders it safely: no alert, no script node, no onerror attribute', shot: 'screenshots/I40-rich-text-record.png' },
  I41: { verdict: 'PASS' }, I42: { verdict: 'PASS' },
  I43: { id: 'I43', verdict: 'NOT RUN', note: 'needs a workflow rule using the field' }, I44: { id: 'I44', verdict: 'NOT RUN', note: 'no telephony integration' },
  I45: { id: 'I45', verdict: 'MISSING', gap: 'Z11', note: 'retest when Z11 is built — seeded standard fields carry isDeletable/canPermanentlyDelete=true (not clicked)' },
  I46: { id: 'I46', verdict: 'NOT RUN', note: 'unused counter not automated' },
  I47: { id: 'I47', verdict: 'NOT RUN', note: 'field dependency rules not automated' }, I48: { id: 'I48', verdict: 'NOT RUN', note: 'not automated' }, I49: { id: 'I49', verdict: 'NOT RUN', note: 'not automated' },
  'F9': { verdict: 'FAIL', severity: 'High', note: 'The required record-name field is not enforced: POST /modules/{id}/records with no name → 201, both with the field off-layout and with layout_id = the default layout (Name on it). The required custom field on the same layout IS enforced (I4).' },
  H5: { verdict: 'INCONCLUSIVE', note: 'Field Properties → PERMISSIONS lets Desk Light Agent have Read and Edit (both ticked by default) — Zoho does not allow Read & Write for Light Agents. Effect on a real Light Agent not tested (no such account).' }
});
fs.writeFileSync(f, JSON.stringify(o, null, 1));
